#!/usr/bin/env python3
"""Auto-detect which applicant-tracking system each company uses.
Reads companies.txt (one per line: "Name" or "Name | careers-page-url"),
probes Greenhouse / Lever / Ashby by likely slugs and scans the careers page
for Workday / ATS links. Writes detected.yaml (read automatically by
job_watcher.py) and unresolved.txt (companies that need a manual source)."""
import re
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import requests
import yaml

ROOT = Path(__file__).parent
HEADERS = {"User-Agent": "Mozilla/5.0 (personal job watcher)"}
T = 20


def slug_candidates(name):
    base = re.sub(r"[^a-z0-9 ]", "", name.lower().replace("&", "and"))
    w = base.split()
    c = ["".join(w), "-".join(w), w[0], "".join(w) + "inc", "".join(w) + "careers"]
    return list(dict.fromkeys(x for x in c if x))


def probe_greenhouse(s):
    r = requests.get(f"https://boards-api.greenhouse.io/v1/boards/{s}/jobs", headers=HEADERS, timeout=T)
    if r.ok:
        jobs = r.json().get("jobs", [])
        return len(jobs), (jobs[0]["title"] if jobs else "")
    return 0, ""


def probe_lever(s):
    r = requests.get(f"https://api.lever.co/v0/postings/{s}", params={"mode": "json"}, headers=HEADERS, timeout=T)
    if r.ok and isinstance(r.json(), list):
        jobs = r.json()
        return len(jobs), (jobs[0]["text"] if jobs else "")
    return 0, ""


def probe_ashby(s):
    r = requests.get(f"https://api.ashbyhq.com/posting-api/job-board/{s}", headers=HEADERS, timeout=T)
    if r.ok:
        jobs = r.json().get("jobs", [])
        return len(jobs), (jobs[0]["title"] if jobs else "")
    return 0, ""


PROBES = {"greenhouse": probe_greenhouse, "lever": probe_lever, "ashby": probe_ashby}
PAGE_PATTERNS = [
    ("workday", r"https://[a-z0-9-]+\.wd\d+\.myworkdayjobs\.com/(?:[a-z]{2}-[A-Z]{2}/)?[A-Za-z0-9_-]+"),
    ("greenhouse", r"(?:boards|job-boards)\.greenhouse\.io/(?:embed/job_board\?for=)?([a-z0-9_-]+)"),
    ("lever", r"jobs\.lever\.co/([a-z0-9_-]+)"),
    ("ashby", r"jobs\.ashbyhq\.com/([a-z0-9_.-]+)"),
]


def detect(line):
    name, _, url = (p.strip() for p in line.partition("|"))
    # 1) careers page scan (most reliable when a URL is given)
    if url:
        try:
            page = requests.get(url, headers=HEADERS, timeout=T).text
            for kind, pat in PAGE_PATTERNS:
                m = re.search(pat, page)
                if m and kind == "workday":
                    return {"name": name, "type": "workday", "url": m.group(0),
                            "search": ["MBA", "intern"]}, "found on careers page"
                if m:
                    n, sample = PROBES[kind](m.group(1))
                    if n:
                        return {"name": name, "type": kind, "slug": m.group(1)}, f"{n} jobs, e.g. {sample}"
        except Exception as e:
            print(f"  {name}: page scan failed ({e})")
    # 2) slug guessing; keep the board with the most jobs (old boards go stale)
    best = None
    for s in slug_candidates(name):
        for kind, probe in PROBES.items():
            try:
                n, sample = probe(s)
            except Exception:
                continue
            if n and (best is None or n > best[0]):
                best = (n, {"name": name, "type": kind, "slug": s}, f"{n} jobs, e.g. {sample}")
    return (best[1], best[2]) if best else (None, "not found")


def main():
    lines = [l.strip() for l in (ROOT / "companies.txt").read_text(encoding="utf-8").splitlines()
             if l.strip() and not l.strip().startswith("#")]
    with ThreadPoolExecutor(8) as ex:
        results = list(ex.map(detect, lines))
    found, missing = [], []
    for line, (entry, note) in zip(lines, results):
        label = line.split("|")[0].strip()
        if entry:
            found.append(entry)
            print(f"OK   {label:28} {entry['type']:10} {entry.get('slug', entry.get('url'))}  ({note})")
        else:
            missing.append(label)
            print(f"MISS {label}")
    (ROOT / "detected.yaml").write_text(
        "# Auto-generated by detect_ats.py. Check the sample titles in the Actions log:\n"
        "# a guessed slug can occasionally belong to a different company.\n"
        + yaml.safe_dump(found, sort_keys=False, allow_unicode=True), encoding="utf-8")
    (ROOT / "unresolved.txt").write_text("\n".join(missing) + "\n", encoding="utf-8")
    print(f"\n{len(found)} detected, {len(missing)} unresolved")


if __name__ == "__main__":
    main()
